### ISSUE TITLE
Optimize blog roadmap

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#270]
- [x] Reduce requests being made to static assets which are not used anymore
- [x] Put old themes into submodules
- [x] Decide what to do with old assets/blogs/designs
- [x] Optimize images
- [x] Improve on the design
- [x] Add Pagination
- [x] Think about pelican plugins
- [x] Add Header image  

Plugin Suggestions
- https://github.com/getpelican/pelican-plugins/tree/master/readtime

and lots of more.

**Comment by Shankhanil** [comment]
It's a cool project. Might I take a look, and can you guide me through it?

**Comment by ananyo2012** [comment]
@Shankhanil I think most of the points need yet to decided by the @pythonindia/pycon-india-2020 team. A new design for the blog is coming up and the older design needs to be scrubbed. 

For now you can do a performance analysis of the blog load time and look out for things that can be done to improve it. Like image optimizations that can be made.

**Comment by Shankhanil** [comment]
Can you guide me on how to go about doing that? any reference I should look at?

**Comment by ananyo2012** [comment]
@Shankhanil You can start with image optimizations. Run the lighthouse tool from chrome Devtools and generate the report. There you can see how much size each image can be compressed.

**Comment by vipulgupta2048** [comment]
Resolved.
